[font]
size = 13.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[window]
opacity = 0.9
blur = true
padding = {x = 5, y = 5 }
decorations = "Transparent"

[scrolling]
history = 10000
multiplier = 3

[colors.primary]
      background= '#272e33'
      foreground= '#d3c6aa'
      dim_foreground = '#828482'
[colors.normal]
      black=   '#414b50'
      red=     '#E66868'
      green=   '#a7c080'
      yellow=  '#dbbc7f'
      blue=    '#7fbbb3'
      cyan=    '#83c092'
      white=   '#d3c6aa'
[colors.bright]
      black=   '#475258'
      red=     '#e67e80'
      green=   '#a7c080'
      yellow=  '#dbbc7f'
      blue=    '#7fbbb3'
      cyan=    '#83c092'
      white=   '#d3c6aa'
[cursor.style]
shape = "UnderLine"
blinking = "off"
